+
go-gogolint:HavePackageComment(¨ÐÝ¾Ï- 
go-gogolint:AllCaps(¨ÐÝ¾Ï-+
go-gogolint:UnderscoreInGoName(¨ÐÝ¾Ï-'
go-gogolint:ReplaceSprintf(¨ÐÝ¾Ï-.
go-gogocyclo:CyclomaticComplexity(¨ÐÝ¾Ï-/
go-gogolint:ReceiverNameConsistent(¨ÐÝ¾Ï-!
go-govet:Unreachable(¨ÐÝ¾Ï-1
go-gounconvert:UnnecessaryConversion(¨ÐÝ¾Ï-0
go-gogolint:UnderscoreInPackageName(¨ÐÝ¾Ï-(
go-gogolint:NotUseBasicType(¨ÐÝ¾Ï-%
go-gogolint:PackageNames(¨ÐÝ¾Ï-(
go-gogolint:NotUseDotImport(¨ÐÝ¾Ï-'
go-gogolint:SpecificSuffix(¨ÐÝ¾Ï-#
go-gogas:SQLFormatting(¨ÐÝ¾Ï-$
go-gogolint:Initialisms(¨ÐÝ¾Ï-$
go-gogolint:FormComment(¨ÐÝ¾Ï- 
go-gogas:WeakCrypto(¨ÐÝ¾Ï-0
go-gogolint:AnnoyingUseExportedType(¨ÐÝ¾Ï-+
go-gogoimports:FileNotImported(¨ÐÝ¾Ï-/
go-gogosimple:ChannelInsteadSelect(¨ÐÝ¾Ï-!
go-gogolint:OmitType(¨ÐÝ¾Ï-/
go-gogolint:StructFieldInitialisms(¨ÐÝ¾Ï-/
go-gogolint:ReceiverNameReflection(¨ÐÝ¾Ï-&
go-gogas:SQLConcatenation(¨ÐÝ¾Ï-.
go-gogolint:Omit2ndValueFromRange(¨ÐÝ¾Ï-,
go-gogolint:PackageCommentSpace(¨ÐÝ¾Ï-'
go-gogolint:ErrorEndString(¨ÐÝ¾Ï-*
go-goerrcheck:ValueNotChecked(¨ÐÝ¾Ï-%
go-gogolint:ErrorVarName(¨ÐÝ¾Ï-&
go-gogolint:IfBlockReturn(¨ÐÝ¾Ï-3
go-go!ineffassign:IneffectualAssignment(¨ÐÝ¾Ï-/
go-gogolint:ContextContextFirstArg(¨ÐÝ¾Ï- 
go-gogas:UnsafeCall(¨ÐÝ¾Ï-,
go-gogolint:ExportedDeclaration(¨ÐÝ¾Ï-*
go-gogolint:ReplaceLintIncDec(¨ÐÝ¾Ï-'
go-gogolint:DropAssignment(¨ÐÝ¾Ï-2
go-go golint:ReceiverNameNotUnderscore(¨ÐÝ¾Ï-,
go-gogolint:ExportedHaveComment(¨ÐÝ¾Ï-
go-go
vet:Shadow(¨ÐÝ¾Ï--
go-gogolint:ExportedHaveComment2(¨ÐÝ¾Ï-/
go-gostructcheck:UnusedStructField(¨ÐÝ¾Ï-,
go-gogas:UnescapedHTMLTemplates(¨ÐÝ¾Ï-%
go-gogas:UnhandledErrors(¨ÐÝ¾Ï-(
go-gogolint:ErrorLastReturn(¨ÐÝ¾Ï-"
go-gogas:RSAKeyLength(¨ÐÝ¾Ï-
go-govet:Lock(¨ÐÝ¾Ï-+
go-gogolint:PackageCommentForm(¨ÐÝ¾Ï-+
go-govet:FormatingPrintfFamily(¨ÐÝ¾Ï-!
go-gogolint:LeadingK(¨ÐÝ¾Ï-,
go-gogolint:CommentExportedType(¨ÐÝ¾Ï-$
go-gogolint:BlankImport(¨ÐÝ¾Ï-
go-go
vet:Misuse(¨ÐÝ¾Ï-